USER_LOGIN='Login successfully.'
USER_CREATED='User registered successfully.'
USER_UPDATE='User updated successfully.'
USER_DELETE='User deleted successfully.'
BOOK_DELETE='Book deleted successfully.'
FORGOT_PASSWORD_MESSAGE='A reset password link has been sent to your email successfully.'
CHANGE_PASSWORD='Password has been updated successfully.'
FOUND='Data found successfully.'
NOT_FOUND='Data not found.'
DATA_FOUND_SUCCESS = "Data found successfully"
NO_USER='User does not exists.'
NO_BOOK='book does not exists.'
USER_ID='Please provide user id.'
BOOK_ID='Please provide book id.'
ACTIVE='Activated successfully.'
INACTIVE='Inactivated successfully.'
PROFILE_UPDATE='Profile updated successfully.'
BOOK_CREATE="Book created successfully."
BOOK_UPDATE="Book updated successfully."
BOOK_DATA='Data Success'
ERROR='Somthing Went Wrong'
EMAILREQUIRED="Email is required."
QRCODE="QR code generated successfully."
NOTLOGIN="Access Denied: Unauthorized Role"
UNAUTHORIZED='Non authorized user'
DASHBOARD="Total count of dashboard"
FEEDBACK_CREATE='Question created successfully.'
DELETE='Delete successfully.'
BOOK_READ='Book read successfully.'
BOOK_FEEDBACK='Feedback submit successfully.'
BOOK_FEEDBACK_UPDATE='Feedback update successfully.'
BOOK_ORDER_UPDATE='Book order update successfully.'
SUBJECT_CREATE="Subject created successfully."
SUBJECT_UPDATE="Subject updated successfully"
SCHOOL_CREATE="School created successfully"
School_UPDATE="School updated successfully"
CITY_CREATE="City created successfully"
CITY_NOT="No cities found"
CITY_DELETE='City Not Found.'
STATE_CREATE="State created successfully"
STATE_UPDATE="State Update successfully"
STATE_DELETE='State Not Found.'
COUNTRY_DELETE='Country Not Found.'
COUNTRY_UPDATE="Country Update successfully"
COUNTRY_CREATE="Country created successfully"
SCHOOL_DELETE='School Not Found.'
SUBJECT_DELETE='Subject Not Found.'
REGIONAL_DELETE='Regional Not Found.'
REGIONAL_UPDATE="Regional Update successfully"
REGIONAL_CREATE="Regional created successfully"

