# Generated by Django 5.1.5 on 2025-02-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_rename_address_userprofile_number_of_outlets_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlet',
            options={'verbose_name': 'Outlet', 'verbose_name_plural': 'Outlets'},
        ),
        migrations.AlterModelOptions(
            name='usermaster',
            options={'verbose_name': 'User Master', 'verbose_name_plural': 'User Masters'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelTable(
            name='outlet',
            table='outlet',
        ),
        migrations.AlterModelTable(
            name='usermaster',
            table='user_master',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(help_text='Include country code (e.g., +91)', max_length=15)),
                ('birthday', models.DateField()),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('age_group', models.CharField(choices=[('10-15', '10-15'), ('16-30', '16-30'), ('31-45', '31-45'), ('>45', 'Above 45')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('visit_frequency', models.CharField(max_length=255)),
                ('date_of_visit', models.DateField()),
                ('favorite_services', models.TextField(blank=True, null=True)),
                ('overall_experience', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('service_quality_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('item_quality_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('value_for_money', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('would_recommend', models.BooleanField(default=False)),
                ('likelihood_to_return', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('emotions', models.CharField(choices=[('Happy', 'Happy'), ('Excited', 'Excited'), ('Neutral', 'Neutral'), ('Disappointed', 'Disappointed'), ('Frustrated', 'Frustrated')], max_length=20)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='v1.outlet')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='v1.userprofile')),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedbacks',
                'db_table': 'customer_feedback',
            },
        ),
    ]
