# Generated by Django 5.1.5 on 2025-03-24 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_membershipplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.CharField(max_length=255)),
                ('training', models.EmailField(max_length=254)),
                ('staff_re_training', models.CharField(max_length=15)),
                ('dedicated_poc', models.CharField(max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_systems', to='v1.membershipplan')),
            ],
            options={
                'verbose_name': 'Support System',
                'verbose_name_plural': 'Support Systems',
                'db_table': 'support_system',
            },
        ),
    ]
