# Generated by Django 5.1.5 on 2025-02-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_alter_customerfeedback_birthday_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
