# Generated by Django 5.1.7 on 2025-04-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_rename_userprofile_msmeprofile_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='razorpay_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='msmeprofile',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='razorpay_order_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='razorpay_payment_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='razorpay_signature',
            field=models.CharField(max_length=255),
        ),
    ]
