# Generated by Django 5.1.5 on 2025-02-17 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfeedback',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='v1.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='whatsapp_number',
            field=models.CharField(max_length=15),
        ),
    ]
