# Generated by Django 5.1.7 on 2025-04-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_alter_subscription_razorpay_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msmeprofile',
            options={'verbose_name': 'MSME Profile', 'verbose_name_plural': 'MSME Profiles'},
        ),
        migrations.AlterModelTable(
            name='msmeprofile',
            table='msme_profile',
        ),
    ]
