# Generated by Django 5.1.7 on 2025-04-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_alter_msmeprofile_options_alter_msmeprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='received', max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Razorpay Webhook Log',
                'verbose_name_plural': 'Razorpay Webhook Logs',
                'db_table': 'Razorpay_webhook_log',
            },
        ),
    ]
