# Generated by Django 5.1.5 on 2025-04-16 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_razorpaywebhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_cutomer_user', to='v1.msmeprofile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_cutomer_user', to='v1.msmeprofile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='user_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ReferralMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True)),
                ('date_referred', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_referral_user', to='v1.msmeprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='v1.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_referral_user', to='v1.msmeprofile')),
            ],
            options={
                'verbose_name': 'Referral master',
                'verbose_name_plural': 'Referral master',
                'db_table': 'referral_master',
            },
        ),
        migrations.CreateModel(
            name='RefereeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True)),
                ('date_referred', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_referee_user', to='v1.msmeprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees_made', to='v1.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_referee_user', to='v1.msmeprofile')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='v1.referralmaster')),
            ],
            options={
                'verbose_name': 'Referee Master',
                'verbose_name_plural': 'Referee Master',
                'db_table': 'referee_master',
            },
        ),
        migrations.CreateModel(
            name='ReferralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_offer', models.IntegerField(blank=True, choices=[(1, 'Discount in %'), (2, 'Discount in INR'), (3, 'Freebie')], null=True)),
                ('selected_offer_text', models.CharField(blank=True, max_length=100, null=True)),
                ('reward_expire_type', models.IntegerField(blank=True, choices=[(1, 'Days'), (2, 'Weeks'), (3, 'Months')], null=True)),
                ('reminder_type', models.IntegerField(blank=True, choices=[(1, 'Days before expiry'), (2, 'Hours before expiry')], null=True)),
                ('reminder_value', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_type', models.IntegerField(blank=True, choices=[(1, 'Contact no.'), (2, 'Website')], null=True)),
                ('contact_value', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_terms', models.JSONField(blank=True, default=list, null=True)),
                ('referrer_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_purchase', models.CharField(blank=True, max_length=50, null=True)),
                ('post_purchase', models.CharField(blank=True, max_length=50, null=True)),
                ('time_unit', models.IntegerField(blank=True, choices=[(1, 'Hours'), (2, 'Minutes')], null=True)),
                ('time_value', models.CharField(blank=True, max_length=50, null=True)),
                ('referee_terms', models.JSONField(blank=True, default=list, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('channels', models.ManyToManyField(to='v1.channel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('msme', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_settings', to='v1.msmeprofile')),
            ],
            options={
                'verbose_name': 'Referral Setting',
                'verbose_name_plural': 'Referral Settings',
                'db_table': 'referral_setting',
            },
        ),
    ]
