# Generated by Django 5.1.5 on 2025-02-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_campaigntype_profession_rewardchoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='anniversary_cate',
            new_name='anniversary_date',
        ),
    ]
