# Generated by Django 5.1.5 on 2025-02-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_channel_remove_campaign_channel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
