# Generated by Django 5.1.5 on 2025-04-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_customer_referral_code_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_cutomer_user', to='v1.customer'),
        ),
    ]
