# Generated by Django 5.1.5 on 2025-02-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_campaign_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
