# Generated by Django 5.1.5 on 2025-02-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_userprofile_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='msme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='v1.userprofile'),
        ),
    ]
