# Generated by Django 5.1.5 on 2025-04-16 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_customer_referral_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_referral_setting_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refereemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_referee_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refereemaster',
            name='date_referred',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='refereemaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_referee_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_referral_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralmaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_referral_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralsetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_referral_setting_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
