# Generated by Django 5.1.5 on 2025-04-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_referralsetting_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereemaster',
            name='referral_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_setting_made', to='v1.referralsetting'),
        ),
        migrations.AddField(
            model_name='referralmaster',
            name='referral_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_setting_made', to='v1.referralsetting'),
        ),
        migrations.AlterField(
            model_name='refereemaster',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referees_made', to='v1.customer'),
        ),
        migrations.AlterField(
            model_name='refereemaster',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='v1.referralmaster'),
        ),
        migrations.AlterField(
            model_name='referralmaster',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='v1.customer'),
        ),
        migrations.AlterField(
            model_name='referralsetting',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='referralsetting',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
