# Generated by Django 5.1.5 on 2025-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_customer_msme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='is_profile_update',
            field=models.BooleanField(default=False),
        ),
    ]
