# Generated by Django 5.1.7 on 2025-04-19 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_refereemaster_referral_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_setting_made', to='v1.referralsetting'),
        ),
    ]
