# Generated by Django 5.1.7 on 2025-04-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_customer_referral_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
