# Generated by Django 5.1.7 on 2025-04-20 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_whatsappcampaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappcampaign',
            options={'verbose_name': 'WhatsApp Campaign', 'verbose_name_plural': 'WhatsApp Campaign'},
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_referee_Customer', to='v1.customer'),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_referee_Customer', to='v1.customer'),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='whatsappcampaign',
            table='whatsApp_campaign',
        ),
    ]
